services:
  - docker
before_install:
  - curl https://raw.githubusercontent.com/cayleygraph/cayley/master/data/testdata.nq > data.nq
  - docker run -d -p 64210:64210 -v $PWD/data.nq:/data.nq cayleygraph/cayley:dev cayley http -i /data.nq
language: node_js
node_js: node
script:
  - npm test
  - npm run docs
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
before_deploy:
  - touch docs/.nojekyll
